# Generated by Django 2.2 on 2021-07-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resulttests',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тестирование', 'verbose_name_plural': 'Тестированиe'},
        ),
    ]
