# Generated by Django 2.2 on 2021-07-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210718_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тестирование', 'verbose_name_plural': 'Тестирования'},
        ),
    ]
