# Generated by Django 2.2 on 2021-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logopedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(null=True, upload_to='audio/', verbose_name='Аудио')),
            ],
            options={
                'verbose_name': 'Логопедия',
                'verbose_name_plural': 'Логопедия',
            },
        ),
    ]
